CREATE SEQUENCE employee."EMPLOYEE_ID_SEQ"
  INCREMENT 2
  MINVALUE 1
  MAXVALUE 9223372036854775807
  START 13
  CACHE 1;

CREATE TABLE employee."EMPLOYEE"
(
  ID integer NOT NULL DEFAULT nextval('"EMPLOYEE_ID_SEQ"'::regclass),
  NAME character varying(20) NOT NULL,
  AGE integer NOT NULL DEFAULT 18,
  JOBTITLE character varying(50),
  CONSTRAINT "EMPLOYEE_PK" PRIMARY KEY (ID)
);

CREATE TABLE employee."PHONE_NUMBER"
(
  EMPLOYEE_FK integer NOT NULL,
  PHONE_NUMBER character varying(15),
  CONSTRAINT "PHONE_NUMBER_EMPLOYEE_FKEY" FOREIGN KEY (EMPLOYEE_FK)
      REFERENCES employee."EMPLOYEE" (ID) MATCH SIMPLE
      ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE employee."EMAIL"
(
  EMPLOYEE_FK integer,
  EMAIL character varying(50),
  CONSTRAINT "EMAIL_EMPLOYEE_FKEY" FOREIGN KEY (EMPLOYEE_FK)
      REFERENCES employee."EMPLOYEE" (ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
);

SET SCHEMA 'employee';